import type { AppSection } from "../types";
import type { UiLanguage } from "../i18n";

export type DemoLanguage = UiLanguage;
export type DemoMode = "contest" | "full";

export interface DemoStep {
  id: string;
  chapter: number;
  name: string;
  section: AppSection;
  target: string;
  patientName?: "Dirk Mayer";
  clearPatientSelection?: boolean;
  revealValueDetail?: boolean;
  durationMs: number;
  subtitle: Record<DemoLanguage, string>;
}

const zhSubtitles: Record<string, string> = {
  introduction: "如何把不同日期的实验室报告作为一个连贯过程阅读？单份报告只描述一个时点，纵向查看则显示时点之间的关系。演示中的已确认数值始终关联报告日期、报告提供的参考范围和原始来源，数据保留在本设备上。导览将从患者概览进入比较、历史和来源核验。",
  dashboard: "哪些患者记录值得进一步查看？表格可同时比较多位患者，并在一行中显示参考范围偏离、明显变化、相关检验组合和长期方向。即使数值仍在报告参考范围内，数学变化也保持可见，从而减少逐份打开报告的需要。",
  "patient-selection": "哪份记录最能展示各视图之间的联系？Dirk Mayer 有三份合成报告，包含可比较的血常规、糖代谢、血脂和肾功能参数。同一组已确认数值可以从概览追踪到报告比较、时间历史和来源核验。此选择不增加医学解释。",
  "analysis-overview": "显示的变化是怎样计算的？比较视图把当前值、匹配的前次值、当前报告提供的参考范围和算术差值放在一起。只有在数值明确可比时才显示绝对和相对变化，因此可以检查展示原因，而不会为计算赋予临床含义。",
  "patient-detail": "两份具体报告之间发生了什么变化？患者详情并列显示选定日期的已确认数值，并保留原始参数名称、单位、参考范围和采集日期。仅当参数和单位一致时才比较，不进行静默换算。",
  profiles: "参数在记录中属于什么专业背景？检验组合把现有数值组织为血常规、糖代谢、血脂和肾功能等熟悉分组。一个参数可以属于多个背景，这些重叠保持透明。分组仅用于组织，不产生发现、诊断、评分或临床优先级。",
  history: "变化只出现在一份报告中，还是跨越多个日期？历史视图按时间排列可比较数值，可区分稳定序列、阶跃变化或持续上升与下降。参考状态仍绑定各报告提供的范围；视图不外推，也不生成预后。",
  provenance: "显示值能否在原始来源中核验？每个已确认工作值都关联合成源文档、报告编号、实验室数值区域、原始名称和技术定位符。打开原始文档会利用该定位符跳到相应报告和数值，使每项提取信息可直接检查。",
  "import-boundary": "提取信息怎样成为已确认工作值？模拟导入视图区分可能的自动提取与明确的人工确认。未来流程可在接受前展示来源、参数、数值、单位和参考范围供核对。本演示禁用文件选择、提取和持久化。",
  conclusion: "完整核验路径保留了什么？患者表支持跨记录比较；详情连接当前值、前次值和报告参考范围；检验组合提供背景，历史提供时间结构，来源追踪把每个确认值带回原始报告。同一份本地合成数据针对不同问题采用不同表示，但含义不被改变。",
  "development-status": "LabDelta 已能汇总实验室数值、显示数学变化和时间过程，并将每个数值关联到原始来源。但它目前明确不判断某项变化是否具有临床相关性或是否需要进一步医学评估。下一阶段需要与医学及高校合作伙伴共同定义和验证：如何区分相关变化与生物、分析波动；如何考虑年龄、性别、妊娠、用药、既往疾病及治疗背景；如何处理不同参考范围、实验室、检测方法和单位；以及变化的幅度、速度、持续时间和重复出现有何意义。还需明确检验组合的定义与重叠、可能提示或排序的标准、不确定性、缺失数据和提取错误的表达方式，并与临床人员开展临床及用户层面的验证。因此，目前的应用有意仅使用合成数据进行演示。"
};

const chapter = (id: string, number: number, name: string, section: AppSection, target: string, en: string, de: string, options: Pick<DemoStep, "patientName" | "clearPatientSelection" | "revealValueDetail"> = {}): DemoStep => ({ id, chapter: number, name, section, target, durationMs: 15000, subtitle: { en, de, "zh-CN": zhSubtitles[id] ?? en }, ...options });

const chapterNames: Record<DemoLanguage, Record<string, string>> = {
  en: {}, de: { Welcome: "Willkommen", Dashboard: "Dashboard", "Patient Selection": "Patientenauswahl", "Analysis Overview": "Analyseübersicht", "Patient Detail": "Patientendetail", Profiles: "Profile", History: "Verlauf", Provenance: "Provenienz", Import: "Import", Closing: "Abschluss", "Current development status and clinical clarification needs": "Aktueller Entwicklungsstand und medizinischer Klärungsbedarf" },
  "zh-CN": { Welcome: "欢迎", Dashboard: "仪表板", "Patient Selection": "患者选择", "Analysis Overview": "分析概览", "Patient Detail": "患者详情", Profiles: "检验组合", History: "历史", Provenance: "来源追踪", Import: "导入", Closing: "结束", "Current development status and clinical clarification needs": "当前开发状态与医学验证需求" }
};
export function localizedChapterName(name: string, language: DemoLanguage): string { return chapterNames[language][name] ?? name; }

export const DEMO_STEPS: readonly DemoStep[] = [
  chapter("introduction", 1, "Welcome", "dashboard", "demo-banner", "How can laboratory findings from separate dates be read as one coherent record? A single report describes one moment. Longitudinal review adds the relationship between those moments. In this demonstration, confirmed values from synthetic reports remain linked to their dates, supplied reference intervals, and original sources. The data stays on this device. The walkthrough follows the same path a reviewer might take: from the patient overview to comparison, history, and verification in the source.", "Wie lassen sich Laborbefunde verschiedener Zeitpunkte als zusammenhängender Verlauf lesen? Ein einzelner Bericht beschreibt zunächst nur einen Moment. Die longitudinale Betrachtung ergänzt die Beziehung zwischen diesen Momenten. In dieser Demonstration bleiben bestätigte Werte synthetischer Berichte mit Datum, geliefertem Referenzintervall und Originalquelle verbunden. Die Daten verbleiben auf diesem Gerät. Der Rundgang folgt einem möglichen Prüfweg: von der Patientenübersicht über Vergleich und Verlauf bis zur Kontrolle in der Quelle."),
  chapter("dashboard", 2, "Dashboard", "dashboard", "dashboard-patient-table", "Which patient records contain values that warrant closer inspection? The table allows several patients to be compared at the same time. Reference deviations, clearly changed values, affected laboratory profiles, and longitudinal directions appear within one row. Changes inside the supplied reference interval remain visible as mathematical changes. This compact representation reduces the need to open and read every report sequentially before identifying which record and which parameter should be examined next.", "Bei welchen Patientenakten lohnt sich eine genauere Prüfung der Veränderungen? In der Tabelle lassen sich mehrere Personen gleichzeitig vergleichen. Referenzabweichungen, deutlich veränderte Werte, betroffene Laborprofile und längerfristige Richtungen stehen in einer Zeile. Auch Veränderungen innerhalb des gelieferten Referenzintervalls bleiben als mathematische Änderungen sichtbar. Die kompakte Darstellung reduziert das sequentielle Öffnen einzelner Berichte und zeigt unmittelbar, welche Akte und welcher Parameter als Nächstes betrachtet werden können."),
  chapter("patient-selection", 3, "Patient Selection", "dashboard", "patient-dirk-mayer", "Which record demonstrates the relationship between the available views most clearly? Dirk Mayer has three synthetic laboratory reports with comparable parameters across blood count, glucose metabolism, lipids, and kidney profiles. The same confirmed values can therefore be followed from the overview into direct report comparison, chronological history, and source verification. Selecting this row does not add an interpretation. It simply opens the existing record with the broadest longitudinal context in the approved demonstration data.", "Bei welcher Akte wird der Zusammenhang der verfügbaren Ansichten besonders deutlich? Für Dirk Mayer liegen drei synthetische Laborberichte mit vergleichbaren Parametern aus Blutbild, Glukosestoffwechsel, Lipiden und Nierenprofil vor. Dieselben bestätigten Werte lassen sich deshalb von der Übersicht in den direkten Berichtsvergleich, den chronologischen Verlauf und die Quellenprüfung verfolgen. Die Auswahl ergänzt keine Interpretation. Sie öffnet lediglich die vorhandene Akte mit dem umfangreichsten longitudinalen Kontext der freigegebenen Demodaten.", { patientName: "Dirk Mayer" }),
  chapter("analysis-overview", 4, "Analysis Overview", "analysis", "value-explanation", "How was a displayed change calculated? The comparison view brings together the current measurement, the matching previous measurement, the reference interval supplied with the current report, and the arithmetic difference. Absolute and relative changes are shown only when the values are directly comparable. This makes the reason for displaying a parameter inspectable without assigning clinical meaning to the calculation. The viewer can distinguish a reference deviation from a mathematical change within the supplied interval.", "Wie wurde eine angezeigte Veränderung berechnet? Die Vergleichsansicht führt den aktuellen Messwert, den passenden Vorwert, das mit dem aktuellen Bericht gelieferte Referenzintervall und die mathematische Differenz zusammen. Absolute und relative Änderungen erscheinen nur bei eindeutig vergleichbaren Werten. Damit bleibt nachvollziehbar, warum ein Parameter gezeigt wird, ohne der Berechnung eine klinische Bedeutung zuzuweisen. Referenzabweichung und mathematische Veränderung innerhalb des gelieferten Intervalls bleiben klar unterscheidbar.", { patientName: "Dirk Mayer", revealValueDetail: true }),
  chapter("patient-detail", 5, "Patient Detail", "reports", "comparison-table", "What changed between two specific reports? Patient Detail places the confirmed measurements from selected report dates side by side. Original parameter labels, units, supplied reference intervals, and collection dates remain visible. Values are compared only when parameter and unit match; no silent conversion is introduced. This view supports a direct check of which measurement changed, by how much, and between which dates, while retaining the report context needed to verify the comparison.", "Was hat sich zwischen zwei konkreten Berichten verändert? Patient Detail stellt die bestätigten Messwerte ausgewählter Berichtszeitpunkte direkt gegenüber. Originalbezeichnungen, Einheiten, gelieferte Referenzintervalle und Entnahmedaten bleiben sichtbar. Werte werden nur verglichen, wenn Parameter und Einheit übereinstimmen; eine stille Umrechnung erfolgt nicht. Dadurch lässt sich direkt prüfen, welcher Messwert sich um welchen Betrag und zwischen welchen Zeitpunkten verändert hat, während der Berichtskontext für die Kontrolle erhalten bleibt.", { patientName: "Dirk Mayer" }),
  chapter("profiles", 6, "Profiles", "profiles", "assigned-profiles", "In which clinical context does a parameter appear in this record? Laboratory profiles organize existing values into familiar groups such as blood count, glucose metabolism, lipids, and kidney parameters. A parameter may belong to more than one context, and those overlaps remain visible. The profile view therefore helps reviewers scan related measurements together without changing the underlying values. The grouping itself is organizational: it does not produce a finding, diagnosis, score, or clinical priority.", "In welchem fachlichen Zusammenhang erscheint ein Parameter in dieser Akte? Laborprofile ordnen vorhandene Werte vertrauten Gruppen wie Blutbild, Glukosestoffwechsel, Lipiden und Nierenparametern zu. Ein Parameter kann mehreren Kontexten angehören; solche Überschneidungen bleiben sichtbar. Die Profilansicht erleichtert damit die gemeinsame Betrachtung zusammengehöriger Messwerte, ohne die zugrunde liegenden Werte zu verändern. Die Gruppierung bleibt organisatorisch und erzeugt weder Befund, Diagnose, Bewertung noch klinische Priorität.", { patientName: "Dirk Mayer" }),
  chapter("history", 7, "History", "history", "parameter-history", "Is a change confined to one report, or is it visible across several dates? The history view orders comparable measurements chronologically. This makes it possible to distinguish a stable sequence from a step change or a continuing rise or fall. Reference status remains tied to the interval supplied with each report. The view describes observed measurements and mathematical direction only; it does not extrapolate beyond the available reports or turn the sequence into a prognosis.", "Ist eine Veränderung auf einen Bericht begrenzt oder über mehrere Zeitpunkte sichtbar? Die Verlaufsansicht ordnet vergleichbare Messwerte chronologisch. Dadurch lassen sich eine stabile Folge, eine sprunghafte Änderung oder ein fortgesetztes Steigen beziehungsweise Fallen unterscheiden. Der Referenzstatus bleibt an das jeweils mitgelieferte Berichtsintervall gebunden. Die Ansicht beschreibt ausschließlich beobachtete Messwerte und mathematische Richtungen. Sie schreibt den Verlauf nicht über die vorhandenen Berichte hinaus fort und erstellt keine Prognose.", { patientName: "Dirk Mayer" }),
  chapter("provenance", 8, "Provenance", "provenance", "provenance", "Can the displayed value be checked against its primary source? Every confirmed working value remains connected to the synthetic source document, report number, laboratory-value section, original label, and technical locator. Documented corrections remain visible as part of that trace. Opening the original document uses this locator to navigate to the corresponding report and value. Provenance therefore separates the convenient working representation from the evidence on which it is based and makes each extracted entry directly verifiable.", "Lässt sich der dargestellte Wert unmittelbar an seiner Primärquelle kontrollieren? Jeder bestätigte Arbeitswert bleibt mit synthetischem Quelldokument, Berichtsnummer, Laborwertbereich, Originalbezeichnung und technischem Locator verbunden. Dokumentierte Korrekturen bleiben als Teil dieser Herkunft sichtbar. Beim Öffnen des Originaldokuments führt der Locator zum zugehörigen Bericht und Messwert. Die Provenienz trennt damit die komfortable Arbeitsdarstellung von ihrer Belegstelle und macht jede extrahierte Angabe direkt überprüfbar.", { patientName: "Dirk Mayer" }),
  chapter("import-boundary", 9, "Import", "import", "import-information", "How should extracted information become a confirmed working value? The simulated import view separates possible automatic extraction from explicit human confirmation. A future workflow could present the source, recognized parameter, value, unit, and reference interval for review before anything is accepted. In this demonstration, file selection, extraction, and persistence are disabled. The screen illustrates only the review boundary: machine-produced suggestions would remain provisional until a person confirms the information against the source document.", "Wie wird aus einer extrahierten Angabe ein bestätigter Arbeitswert? Die simulierte Importansicht trennt eine mögliche automatische Extraktion von der ausdrücklichen menschlichen Bestätigung. Ein zukünftiger Ablauf könnte Quelle, erkannten Parameter, Wert, Einheit und Referenzintervall vor der Übernahme zur Prüfung vorlegen. In dieser Demonstration sind Dateiauswahl, Extraktion und Speicherung deaktiviert. Die Ansicht zeigt ausschließlich die Prüfgrenze: maschinell erzeugte Vorschläge blieben vorläufig, bis eine Person die Angaben anhand des Quelldokuments bestätigt."),
  chapter("conclusion", 10, "Closing", "dashboard", "dashboard-overview", "What does the complete review path preserve? The patient table supports comparison across records. The detailed views connect a current value with its previous measurement and supplied reference. Profiles provide context, history provides chronological structure, and provenance returns every confirmed value to its source. The same local synthetic data is represented differently for each question, without changing its meaning. The result is a traceable path from overview to individual measurement and back to the original report.", "Was bleibt über den gesamten Prüfweg erhalten? Die Patiententabelle ermöglicht den Vergleich mehrerer Akten. Die Detailansichten verbinden aktuellen Wert, Vorwert und gelieferte Referenz. Profile liefern fachlichen Kontext, der Verlauf die zeitliche Struktur und die Provenienz führt jeden bestätigten Wert zur Quelle zurück. Dieselben lokalen synthetischen Daten werden für unterschiedliche Fragestellungen verschieden dargestellt, ohne ihre Bedeutung zu verändern. So entsteht ein nachvollziehbarer Weg von der Übersicht zum einzelnen Messwert und zurück zum Originalbericht.", { clearPatientSelection: true }),
  chapter("development-status", 11, "Current development status and clinical clarification needs", "limitations", "development-status", "LabDelta consolidates laboratory values, shows mathematical changes and chronological courses, and connects each value to its original source. It does not decide whether a change is clinically relevant or requires assessment. That step requires cooperation and validation with medical and university partners. Work must distinguish relevant change from biological and analytical variation; account for age, sex, pregnancy, medication, pre-existing conditions, and treatment context; and reconcile different reference ranges, laboratories, methods, and units. It must clarify the meaning of magnitude, speed, duration, and recurrence; define laboratory profiles, overlaps, and criteria for possible notices or prioritization; represent uncertainty, missing data, and extraction errors; and undergo clinical and user validation with physicians. This unresolved boundary explains the synthetic-data demonstration.", "LabDelta kann Laborwerte zusammenführen, mathematische Veränderungen und zeitliche Verläufe darstellen und jeden Wert mit seiner Originalquelle verbinden. Es entscheidet nicht, ob eine Veränderung klinisch relevant ist oder weitere medizinische Abklärung erfordert. Dieser Schritt benötigt Kooperation und Validierung mit medizinischen und universitären Partnern. Zu klären sind die Abgrenzung relevanter Veränderungen von biologischer und analytischer Schwankung; Alter, Geschlecht, Schwangerschaft, Medikamente, Vorerkrankungen und Behandlungskontext; unterschiedliche Referenzbereiche, Labore, Messmethoden und Einheiten; sowie Höhe, Geschwindigkeit, Dauer und Wiederholung einer Veränderung. Hinzu kommen Definition und Überschneidung von Laborprofilen, Kriterien für mögliche Hinweise oder Priorisierung, die Darstellung von Unsicherheit, fehlenden Daten und Extraktionsfehlern sowie klinische und nutzerbezogene Validierung mit ärztlichen Partnern. Diese offene fachliche Grenze erklärt die bewusste Beschränkung auf eine Demonstration mit synthetischen Daten.", { clearPatientSelection: true })
] as const;

const CONTEST_STEP_IDS = new Set(["introduction", "dashboard", "analysis-overview", "history", "provenance", "development-status"]);
export const CONTEST_DEMO_STEPS: readonly DemoStep[] = DEMO_STEPS.filter(step => CONTEST_STEP_IDS.has(step.id));
export function stepsForMode(mode: DemoMode): readonly DemoStep[] { return mode === "contest" ? CONTEST_DEMO_STEPS : DEMO_STEPS; }
