import { Database, FileText, MapPin, RefreshCw, UserRound } from "lucide-react";
import { parameterAnchorKey } from "../data/syntheticDocument";
import { useI18n, workspaceText } from "../i18n";
import type { ConfirmedReportValue, LaboratoryReport, PatientDetails, PatientListItem, ProvenanceLocator } from "../types";
import { CollapsiblePanel } from "./CollapsiblePanel";
import { SyntheticDocumentView } from "./SyntheticDocumentView";

interface Props { patients: PatientListItem[]; selectedPatient: PatientListItem | null; patientDetails: PatientDetails | null; reports: LaboratoryReport[]; selectedReport: LaboratoryReport | null; values: ConfirmedReportValue[]; isLoadingPatients: boolean; isLoadingPatientData: boolean; isLoadingValues: boolean; patientsError: string | null; patientDataError: string | null; valuesError: string | null; onRefreshPatients: () => Promise<void>; onSelectPatient: (id: string) => void; onSelectReport: (id: string) => void; }
function locator(locator: ProvenanceLocator): string { if (locator.kind === "jsonPath") return locator.path; if (locator.kind === "page") return String(locator.pageNumber); if (locator.kind === "tableCell") return `${locator.rowNumber} · ${locator.columnName}`; if (locator.kind === "textSpan") return `${locator.startOffset}–${locator.endOffset}`; return "—"; }

export function DemoDataWorkspace(props: Props) {
  const { language, t } = useI18n();
  const w = (key: Parameters<typeof workspaceText>[1]) => workspaceText(language, key);
  const openOriginal = (parameter: string) => document.querySelector<HTMLElement>(`[data-demo-target="original-document"] [data-parameter-key="${parameterAnchorKey(parameter)}"]`)?.scrollIntoView({ behavior: "smooth", block: "center" });
  if (props.isLoadingPatients) return <section className="demo-state" aria-live="polite">{w("loading")}</section>;
  if (props.patientsError) return <section className="demo-state error-state" role="alert"><strong>{w("loadError")}</strong><span>{props.patientsError}</span><button className="outline-button" type="button" onClick={() => void props.onRefreshPatients()}><RefreshCw size={15} /> {t("retry")}</button></section>;
  if (!props.patients.length) return <section className="demo-state"><Database size={32} /><strong>{w("noStored")}</strong><span>{t("emptyPatients")}</span></section>;
  return <div className="demo-data-layout">
    <aside className="demo-patient-list" aria-label={t("syntheticPatients")}><div className="demo-section-heading"><div><span>{t("localSqlite")}</span><h1>{t("syntheticPatients")}</h1></div><button aria-label={t("refresh")} className="icon-button" type="button" onClick={() => void props.onRefreshPatients()}><RefreshCw size={16} /></button></div>{props.patients.map(patient => <button className={patient.id === props.selectedPatient?.id ? "demo-patient-option selected" : "demo-patient-option"} key={patient.id} type="button" onClick={() => props.onSelectPatient(patient.id)}><UserRound size={17} /><span><strong>{patient.displayName}</strong><small>{patient.dateOfBirth} · {patient.id}</small></span></button>)}</aside>
    <section className="demo-record-view" aria-label={w("patientDetail")}>
      {props.isLoadingPatientData ? <div className="demo-state compact" aria-live="polite">{w("loading")}</div> : props.patientDataError ? <div className="demo-state compact error-state" role="alert"><strong>{w("loadError")}</strong><span>{props.patientDataError}</span></div> : props.patientDetails ? <>
        <CollapsiblePanel demoTarget="patient-detail" storageKey="patient-detail" title={w("patientDetail")}><header className="demo-record-header"><div className="avatar">{props.patientDetails.displayName.split(" ").map(part => part[0]).join("")}</div><div><span>{w("selectedPatient")}</span><h2>{props.patientDetails.displayName}</h2><p>{t("dateOfBirth")}: {props.patientDetails.dateOfBirth} · ID: {props.patientDetails.externalIdentifier ?? w("notSupplied")}</p>{props.patientDetails.bodyMeasurements.length ? <p>{props.patientDetails.bodyMeasurements.map(item => `${item.kind}: ${item.originalValueText} ${item.originalUnit}`).join(" · ")}</p> : null}</div></header></CollapsiblePanel>
        <CollapsiblePanel demoTarget="profile-overview" storageKey="laboratory-profiles" title={w("laboratoryProfiles")}><section className="profile-assignment-panel" data-demo-target="assigned-profiles"><div><h3>{w("assignedProfiles")}</h3><p>{w("profileHelp")}</p></div><div className="profile-assignment-list">{props.patientDetails.profiles.map(profile => <article key={`${profile.id}-${profile.version}`}><strong>{profile.name} <small>v{profile.version}</small></strong><span>{profile.parameterNames.join(", ")}</span></article>)}</div></section></CollapsiblePanel>
        <div className="demo-report-layout">
          <CollapsiblePanel className="report-history-panel" demoTarget="parameter-history" storageKey="parameter-history" title={w("parameterHistory")}><nav className="demo-report-list" aria-label={w("laboratoryReports")} data-demo-target="report-history"><h3><FileText size={16} /> {w("laboratoryReports")}</h3>{!props.reports.length ? <p className="inline-empty">{w("noReports")}</p> : props.reports.map(report => <button className={report.id === props.selectedReport?.id ? "demo-report-option selected" : "demo-report-option"} key={report.id} type="button" onClick={() => props.onSelectReport(report.id)}><strong>{report.specimenCollectedAt ?? w("notSupplied")}</strong><span>{report.laboratoryName ?? w("notSupplied")}</span><small>v{report.revisionNumber ?? "—"}</small></button>)}</nav><div className="parameter-history-anchors"><strong>{w("parameterHistory")}</strong><div>{props.values.slice(0, 8).map(value => <span data-parameter-key={parameterAnchorKey(value.original.parameterName)} key={value.id}>{value.original.parameterName}</span>)}</div></div></CollapsiblePanel>
          <CollapsiblePanel className="comparison-panel" demoTarget="comparison-table" storageKey="comparison-table" title={w("reportValues")}><div className="demo-report-detail">{props.selectedReport ? <><div className="report-metadata"><div><span>{w("specimen")}</span><strong>{props.selectedReport.specimenCollectedAt ?? w("notSupplied")}</strong></div><div><span>{w("laboratory")}</span><strong>{props.selectedReport.laboratoryName ?? w("notSupplied")}</strong></div><div><span>{w("released")}</span><strong>{props.selectedReport.reportReleasedAt ?? w("notSupplied")}</strong></div></div>{props.isLoadingValues ? <div className="demo-state compact">{w("loadingValues")}</div> : props.valuesError ? <div className="demo-state compact error-state" role="alert"><strong>{w("valuesError")}</strong><span>{props.valuesError}</span></div> : !props.values.length ? <div className="demo-state compact"><strong>{w("noValues")}</strong></div> : <ValueTable patient={props.patientDetails} values={props.values} openOriginal={openOriginal} />}</> : props.reports.length ? <div className="demo-state compact">{w("selectReport")}</div> : null}</div></CollapsiblePanel>
        </div>
        <CollapsiblePanel demoTarget="original-document" storageKey="original-document" subtitle={w("generatedDocument")} title={w("originalDocument")}>{props.selectedReport && !props.isLoadingValues && props.values.length ? <SyntheticDocumentView patient={props.patientDetails} report={props.selectedReport} values={props.values} /> : <p className="inline-empty">{w("selectDocument")}</p>}</CollapsiblePanel>
      </> : <div className="demo-state compact">{w("selectPatient")}</div>}
    </section>
  </div>;
}

function ValueTable({ patient, values, openOriginal }: { patient: PatientDetails; values: ConfirmedReportValue[]; openOriginal: (parameter: string) => void }) {
  const { language, t } = useI18n(); const w = (key: Parameters<typeof workspaceText>[1]) => workspaceText(language, key);
  return <div className="confirmed-values-wrap" data-demo-target="confirmed-values"><table className="confirmed-values"><thead><tr><th>{w("originalParameter")}</th><th>{w("confirmedValue")}</th><th>{w("unit")}</th><th>{t("suppliedReference")}</th><th>{w("provenanceLocation")}</th></tr></thead><tbody>{values.map((value, index) => <tr data-demo-target={index === 0 ? "provenance" : undefined} data-parameter-key={parameterAnchorKey(value.original.parameterName)} data-working-value-id={value.id} key={value.id}><td><strong>{value.original.parameterName}</strong><small>{value.original.valueText}</small></td><td><strong>{value.confirmedValue.value}</strong><small>{w("explicitlyConfirmed")} · v{value.versionNumber}</small></td><td>{value.unit ?? w("notSupplied")}</td><td>{value.original.suppliedReferenceRange ?? w("notSupplied")}</td><td><span className="provenance-line"><MapPin size={14} /> {t("source")}</span><strong>{patient.displayName} – {t("reports")}</strong><small><b>{t("location")}</b><br />{t("laboratoryValues")} · {value.original.parameterName}</small><small className="technical-path"><b>{t("technicalPath")}</b><br />{locator(value.provenance.locator)}</small><small>{t("remark")}: {value.provenance.textExcerpt ?? t("noExcerpt")}</small><button className="open-original-link" onClick={() => openOriginal(value.original.parameterName)} type="button">{w("openOriginal")}</button></td></tr>)}</tbody></table></div>;
}
